name: 'Build and push to docker hub'

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Extract tags
        run: echo ${GITHUB_REF/refs\/tags\//}
        id: tagged
      
      - name: Test output tag
        run: echo ${{ steps.tagged.outputs }}

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_HUB_USERNAME }}
      #     password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # - name: Extract metadata (tags, labels) for Docker
      #   id: meta
      #   uses: docker/metadata-action@v4.1.1
      #   with:
      #     images: ${{ secrets.DOCKER_HUB_REPO }}
      #     tags: |
      #       type=sha
      #       type=raw,value=latest

      # - name: Build and push
      #   uses: docker/build-push-action@v3.2.0
      #   with:
      #     push: true
      #     tags: ${{ steps.meta.outputs.tags }}
      #     labels: ${{ steps.meta.outputs.labels }}
      #     context: .
      #     file: Dockerfile